name: 'UnitDemo'
description: '目标是让swift语言成为工作流的工具库瑞士军刀，协助更好的应用githubworkflow'
inputs:
  argOne:  # id of input
    description: '编译或单元测试'
    required: true
    default: 'build'
runs:
  using: "composite"  #Required You must set this value to 'composite'.
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - if: ${{ inputs.argOne == 'build' }}
      run: |
        cd ${{ github.action_path }}
        swift build
        ls -al
        .build/x86_64-apple-macosx/debug/UnitDemo lane hello
      shell: bash
    - if: ${{ inputs.argOne == 'test'}}
      run: swift test
      shell: bash
