name: 'UnitDemo'
description: '目标是让swift语言成为工作流的工具库瑞士军刀，协助更好的应用githubworkflow'
inputs:
  argOne:  # id of input
    description: '编译或单元测试'
    required: true
    default: 'build'
runs:
  using: "composite"  #Required You must set this value to 'composite'.
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - if: ${{ inputs.argOne == 'build' }}
      run: |
        #/Users/runner/work/_actions/it-boyer/UnitDemo/main/Sources/UnitLib/Test
        cd ${{ github.action_path }} #$GITHUB_ACTION_PATH/script.sh
        swift build
        ln -sf .build/x86_64-apple-macosx/debug/Unit Unit
        Unit lane hello
      shell: bash
    - if: ${{ inputs.argOne == 'test'}}
      run: swift test
      shell: bash
