name: 'UnitDemo'
description: '目标是让swift语言成为工作流的工具库瑞士军刀，协助更好的应用githubworkflow'
inputs:
  argOne:  # id of input
    description: '编译或单元测试'
    required: true
    default: 'build'
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.argOne }} == 'build'
      run: swift build
      shell: bash
    - if: ${{ inputs.argOne }} == 'test'
      run: swift test
      shell: bash
