name: Action Helloworld
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        #uses: it-boyer/UnitDemo@v1 #使用tag
        #uses: it-boyer/UnitDemo@main #使用分支
        uses: ./.github/actions/hello #使用本地文件action
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
